FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gfortran \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

COPY Backend/requirements.txt .

RUN pip install --no-cache-dir \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    -r requirements.txt

COPY Backend/ .

EXPOSE 7860

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
